### ISSUE TITLE
使用hyperf的@Middleware注解只加在一个方法，会应用到两个方法上

### ISSUE THREAD

**Issue by canxiaochen** [kakuilan/hyperf-apihelper#12]
use Hyperf\HttpServer\Annotation\Middleware;

  /**
     * @Middleware(TestMiddleware::class)
     * @Post(path="/test/test1")
     * @ApiResponse(code=200, schema={"$ref": "Response"})
     */
    public function test1(RequestInterface $request){}

  /**
     * @Post(path="/test/test2")
     * @ApiResponse(code=200, schema={"$ref": "Response"})
     */
    public function test2(RequestInterface $request){}

**Comment by kakuilan** [comment]
谢谢提出，v0.2.8已修复，麻烦你再测试下看看

**Comment by canxiaochen** [comment]
好了
