### ISSUE TITLE
@ApiController(prefix="/admin" 不起作用

### ISSUE THREAD

**Issue by nirvana72** [kakuilan/hyperf-apihelper#15]
@ApiController(prefix="/admin" 不起作用

`<?php
declare(strict_types=1);

namespace App\Controller\Admin;
use App\Controller\BaseController;
use Hyperf\Apihelper\Annotation\ApiController;
use Hyperf\Apihelper\Annotation\ApiVersion;
use Hyperf\Apihelper\Annotation\ApiResponse;
use Hyperf\Apihelper\Annotation\Method\Post;
use Hyperf\Apihelper\Annotation\Param\Query;
/**
 * @ApiController(prefix="/admin", tag="Administrator", description="管理员权限控制")
 * @ApiVersion(group="v1", description="第一版本")
 */
class AdministratorController extends BaseController  {

  /**
   * @Post(path="/login", summary="登录", description="管理后台登录")
   * @Query(key="account", rule="required|string|trim")
   * @Query(key="password", rule="required|string|trim")
   * @Query(key="captcha", rule="required|string|size:6")
   * @Query(key="random_code", rule="required|string|size:6")
   * @ApiResponse(code=200, schema={"$ref":"Response"})
   */
  public function login() {
    $account = $this->request->query('account');
    return self::doSuccess($account);
  }
}`

**Comment by kakuilan** [comment]
我看看

**Comment by kakuilan** [comment]
已修复，请升级到v0.4.8
