### ISSUE TITLE
@ApiController(prefix="/admin" 仍有BUG

### ISSUE THREAD

**Issue by nirvana72** [kakuilan/hyperf-apihelper#16]
最后生成的路由是 http://localhost:9501admin/captcha?random_code=123123
前面少了个 /

**Comment by kakuilan** [comment]
贴下代码

**Comment by nirvana72** [comment]
![image](https://user-images.githubusercontent.com/15214079/100305002-09947680-2fdb-11eb-816c-7837671836c8.png)

**Comment by kakuilan** [comment]
是我疏忽了，再更新v0.4.9试下

**Comment by nirvana72** [comment]
😃 it works
