### ISSUE TITLE
引入apihelper包后，@AutoController注解失效

### ISSUE THREAD

**Issue by bestlake** [kakuilan/hyperf-apihelper#18]
引入apihelper包后，@AutoController注解失效

**Comment by kakuilan** [comment]
麻烦贴下代码

**Comment by kakuilan** [comment]
目前apihelper不支持@AutoController,因为@ApiController自身已有路由绑定,两者不能共存

**Comment by bestlake** [comment]
/**
     * 初始化注解路由
     * @param array $collector
     * @throws ReflectionException
     */
    protected function initAnnotationRoute(array $collector): void {
        //调用父类注解路由
        parent::initAnnotationRoute($collector);

加上调用父类注解路由后两种路由均能访问。但出现一个诡异的问题是，composer dump -o + 首次启动服务，访问接口请求时会报：[ERROR] Call to a member function make() on null[122] in /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/kakuilan/hyperf-apihelper/src/Validation/Validator.php

**Comment by kakuilan** [comment]
这样是可以，但会引起AutoController和ApiController的路由绑定混乱；
而且本组件不会去处理AutoController相关的东西，我在考虑是否有必要支持它。

**Comment by bestlake** [comment]
[
[hyperf-skeleton.tar.gz](https://github.com/kakuilan/hyperf-apihelper/files/5840248/hyperf-skeleton.tar.gz)
] 这是错误示例。

http://0.0.0.0:9501/index/auto，正常

http://0.0.0.0:9501/v1/hello/test/company2，正常

http://0.0.0.0:9501/v1/hello/user?id=5&u=http%3A%2F%2Fbaidu.com&t=t&e=e&h=h，报：[ERROR] Call to a member function make() on null[122] in /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/kakuilan/hyperf-apihelper/src/Validation/Validator.php
二次启动后，访问：http://0.0.0.0:9501/v1/hello/user?id=5&u=http%3A%2F%2Fbaidu.com&t=t&e=e&h=h，不报错，正常输出json数据。

**Comment by kakuilan** [comment]
嗯，我有空看看

**Comment by kakuilan** [comment]
用了你的示例，不能重现

**Comment by kakuilan** [comment]
文档忘了加ValidationInterface  
修改config/autoload/dependencies.php依赖配置,如
```php
return [
    Hyperf\Apihelper\Validation\ValidationInterface::class => Hyperf\Apihelper\Validation\Validator::class,
    Hyperf\HttpServer\Router\DispatcherFactory::class => Hyperf\Apihelper\DispatcherFactory::class
];
```
