### ISSUE TITLE
@AutoController有效了，但首次运行validator为null

### ISSUE THREAD

**Issue by bestlake** [kakuilan/hyperf-apihelper#19]
minghuhuang@minghuhuang-2:~/workspace/hyperf-skeleton$composer dump -o
Generating optimized autoload files
> rm -rf runtime/container
Generated optimized autoload files containing 4129 classes
minghuhuang@minghuhuang-2:~/workspace/hyperf-skeleton$php bin/hyperf.php start

[ERROR] Call to a member function make() on null[122] in /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/kakuilan/hyperf-apihelper/src/Validation/Validator.php
[ERROR] #0 /Volumes/DevDisk/workspace/hyperf-skeleton/runtime/container/proxy/Hyperf_Apihelper_Middleware_ApiValidationMiddleware.proxy.php(222): Hyperf\Apihelper\Validation\Validator->validate(Array, Array, Array, Object(App\Controller\TestController))
#1 /Volumes/DevDisk/workspace/hyperf-skeleton/runtime/container/proxy/Hyperf_Apihelper_Middleware_ApiValidationMiddleware.proxy.php(170): Hyperf\Apihelper\Middleware\ApiValidationMiddleware->checkRules(Array, Array, Array, Object(App\Controller\TestController))
#2 /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/hyperf/dispatcher/src/AbstractRequestHandler.php(64): Hyperf\Apihelper\Middleware\ApiValidationMiddleware->process(Object(Hyperf\HttpMessage\Server\Request), Object(Hyperf\Dispatcher\HttpRequestHandler))
#3 /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/hyperf/dispatcher/src/HttpRequestHandler.php(26): Hyperf\Dispatcher\AbstractRequestHandler->handleRequest(Object(Hyperf\HttpMessage\Server\Request))
#4 /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/hyperf/dispatcher/src/HttpDispatcher.php(40): Hyperf\Dispatcher\HttpRequestHandler->handle(Object(Hyperf\HttpMessage\Server\Request))
#5 /Volumes/DevDisk/workspace/hyperf-skeleton/vendor/hyperf/http-server/src/Server.php(116): Hyperf\Dispatcher\HttpDispatcher->dispatch(Object(Hyperf\HttpMessage\Server\Request), Array, Object(Hyperf\HttpServer\CoreMiddleware))
#6 {main}

ctrl+c后，再次start服务，则并不会报validator为null的错。

http://0.0.0.0:9501/index/auto（正常）
http://0.0.0.0:9501/v1/hello/test/company2（正常）
http://0.0.0.0:9501/v1/hello/user?id=5&u=http%3A%2F%2Fbaidu.com&t=t&e=e&h=h（第一次报错，重启服务后正常）

[hyperf-skeleton.tar.gz](https://github.com/kakuilan/hyperf-apihelper/files/5840866/hyperf-skeleton.tar.gz)

**Comment by bestlake** [comment]
return [
    Hyperf\Apihelper\Validation\ValidationInterface::class => Hyperf\Apihelper\Validation\Validator::class,
    Hyperf\HttpServer\Router\DispatcherFactory::class => Hyperf\Apihelper\DispatcherFactory::class,
];
dependencies配置信息

**Comment by kakuilan** [comment]
你的swoole是啥版本？

**Comment by bestlake** [comment]
minghuhuang@minghuhuang-2:~/workspace$php --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.1
Built => Jan 13 2021 16:03:15
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1h  22 Sep 2020
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
minghuhuang@minghuhuang-2:~/workspace$php -v
PHP 7.4.2 (cli) (built: Feb 17 2020 12:56:02) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

mac 11.1操作系统

**Comment by kakuilan** [comment]
已修复,升级到0.5.1版本
依赖不用写
Hyperf\Apihelper\Validation\ValidationInterface::class => Hyperf\Apihelper\Validation\Validator::class,
