### ISSUE TITLE
关于apihelper的疑问

### ISSUE THREAD

**Issue by PandaLIU-1111** [kakuilan/hyperf-apihelper#2]
1.如何获取验证完的数据
2.能否开放数据返回格式规范修改
3. `@Body` 能不能定义body里面的内容

**Comment by kakuilan** [comment]
1. 在控制器里面直接使用hyperf的方法去获取,取到的数据都已经过处理,如:
$this->request->query('len');
$this->request->post();
$this->request->route('id');

2. 自定义返回数据格式,这个下一版本考虑加进去
3. 你可以加一个控制器验证方法去检查所需的格式

具体参考下文档说明里的[使用]块

**Comment by kakuilan** [comment]
@PandaLIU-1111 
新版本已支持自定义响应体结构,详情查看说明文档
