### ISSUE TITLE
参数验证失败后，第二次传正确的参数还是报参数错误

### ISSUE THREAD

**Issue by canxiaochen** [kakuilan/hyperf-apihelper#3]

**Comment by canxiaochen** [comment]
src/Validation/Validator.php
文件中 $errors是类属性，在hyperf中，会沿用上次请求的错误信息

**Comment by kakuilan** [comment]
@canxiaochen 
我这边的环境:
- swoole 4.4.17
- hyperf 1.1.26
- hyperf-apihelper 0.1.7

不能重现你的问题.
请问你的环境是怎样的,顺便贴下具体的代码?

**Comment by kakuilan** [comment]
v0.2.0版本已修改,你试下

**Comment by canxiaochen** [comment]
可以了
