### ISSUE TITLE
hyperf自带的验证规则失效

### ISSUE THREAD

**Issue by canxiaochen** [kakuilan/hyperf-apihelper#4]
/**
     * @Get(path="/user", summary="用户信息", description="用户信息")
     * @Query(key="id",  description="id", rule="required|int|gt:0")
     * @ApiResponse(code=200, schema={"$ref": "Response"})
     */

会跳过required|int|gt:0 这些验证

**Comment by kakuilan** [comment]
谢谢反馈,v0.2.1版已修复,你再试下

**Comment by canxiaochen** [comment]
好了
