### ISSUE TITLE
对接口的返回结果自定义生成swagger文档，要怎么做呢

### ISSUE THREAD

**Issue by canxiaochen** [kakuilan/hyperf-apihelper#6]
@ApiResponse(code=200, schema={"$ref": "Response"})

**Comment by kakuilan** [comment]
目前还不支持生成自定义响应体的swagger文档

**Comment by kakuilan** [comment]
你可以参考文档中[自定义响应体结构]部分.
@ApiResponse(code=200, schema={"$ref": "Response"})
上述中的Response结构对应getResponseSchema()返回的结果,是固定的结构.
对Response中多层次的模型输出文档,有点复杂,还没想好怎么做.

**Comment by canxiaochen** [comment]
如果@ApiResponse(code=200, schema={"$ref": "Response"})中的schema传swagger响应示例的json：
@ApiResponse(code=200, schema={"user_id": 1,"name":"张三"})
生成swagger文档时，再结合$baseSchema结构组装生成responses definitions
可行吗？

**Comment by kakuilan** [comment]
这个不是很妥当，我再考虑

**Comment by kakuilan** [comment]
v0.2.3版本已支持自定义swagger model功能,具体请参考文档,麻烦帮忙测试看看还有啥问题不

**Comment by kakuilan** [comment]
v0.2.4版本又改了一些,你可以参考文档[4.3自定义多层级swagger model]以及[2.使用]的末尾部分.
